import { parse } from "smol-toml";
import type { Field, Kind, Plugin, Schema } from "./schema";
import { findPlugin } from "./schema";

/** One plugin chosen in the constructor with the values typed for its fields. */
export interface PluginChoice {
  type: string;
  values: Record<string, string>;
}

/** Everything the constructor collects; a single instance in this version. */
export interface ConfigDraft {
  name: string;
  interval: string;
  retriever: PluginChoice;
  provider: PluginChoice;
}

export interface Generated {
  toml: string;
  /** Template of the environment file that holds the secrets. */
  env: string;
  /** Names of required fields that are still empty. */
  missing: string[];
}

/** Name of the environment variable that carries a secret field, e.g. CLOUDFLARE_TOKEN. */
export function envName(plugin: string, field: string): string {
  return `${plugin}_${field}`.toUpperCase().replace(/[^A-Z0-9]/g, "_");
}

function quote(s: string): string {
  const escaped = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

/** Renders a typed value, or undefined when the text does not fit the type. */
export function renderValue(
  field: Pick<Field, "type">,
  raw: string,
): string | undefined {
  const v = raw.trim();
  switch (field.type) {
    case "boolean":
      return v === "true" || v === "false" ? v : undefined;
    case "integer":
      return /^-?\d+$/.test(v) ? v : undefined;
    case "number":
      return /^-?\d+(\.\d+)?$/.test(v) ? v : undefined;
    case "string":
    case "duration":
      return quote(raw);
    default:
      return undefined;
  }
}

function pluginLines(
  prefix: string,
  plugin: Plugin,
  choice: PluginChoice,
  out: { env: string[]; missing: string[] },
): string[] {
  const lines = [`[[${prefix}]]`, `type = ${quote(plugin.name)}`];
  for (const field of plugin.fields) {
    if (field.secret) {
      // A secret is never typed into the page: the config reads it from the environment.
      if (!field.required && !(choice.values[field.name] ?? "").trim())
        continue;
      const name = envName(plugin.name, field.name);
      lines.push(`${field.name} = ${quote(`\${${name}}`)}`);
      out.env.push(`${name}=`);
      continue;
    }
    const raw = choice.values[field.name] ?? "";
    if (raw.trim() === "") {
      if (field.required) {
        out.missing.push(`${plugin.name}.${field.name}`);
        lines.push(`${field.name} = ""`);
      }
      continue;
    }
    const rendered = renderValue(field, raw);
    if (rendered === undefined) {
      out.missing.push(`${plugin.name}.${field.name}`);
      continue;
    }
    lines.push(`${field.name} = ${rendered}`);
  }
  return lines;
}

/** Writes the configuration for the draft. The schema decides which fields exist and which are secret. */
export function generate(draft: ConfigDraft, schema: Schema): Generated {
  const retriever = findPlugin(schema, "retriever", draft.retriever.type);
  const provider = findPlugin(schema, "provider", draft.provider.type);
  if (!retriever || !provider) throw new Error("unknown plugin in the draft");

  const out = { env: [] as string[], missing: [] as string[] };
  const retrieverLines = pluginLines(
    "instance.retriever",
    retriever,
    draft.retriever,
    out,
  );
  const providerLines = pluginLines(
    "instance.provider",
    provider,
    draft.provider,
    out,
  );

  const toml = [
    "# Generated by dnspatch builder. Save as dnspatch.toml.",
    "# Values like ${NAME} are read from the environment; see the .env file.",
    "",
    `interval = ${quote(draft.interval || "5m")}`,
    "",
    "[[instance]]",
    `name = ${quote(draft.name || "home")}`,
    "",
    ...retrieverLines,
    "",
    ...providerLines,
    "",
  ].join("\n");

  const env = out.env.length
    ? `${["# Secrets for dnspatch. Fill in the values and keep this file private.", ...out.env].join("\n")}\n`
    : "";
  return { toml, env, missing: out.missing };
}

export interface UsedPlugin {
  kind: Kind;
  name: string;
}

export interface Usage {
  plugins: readonly UsedPlugin[];
  /** An instance sets ping_url, which needs the "ping" build tag. */
  ping: boolean;
}

const kinds: Record<string, Kind> = {
  retriever: "retriever",
  provider: "provider",
  notify: "notifier",
};

function isTable(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

/** Reads a pasted configuration and lists the plugin types and features it uses. Throws on invalid TOML. */
export function usageOf(text: string): Usage {
  const doc = parse(text);
  const found = new Map<string, UsedPlugin>();
  let ping = false;

  const add = (kind: Kind, table: unknown) => {
    if (isTable(table) && typeof table.type === "string")
      found.set(`${kind}/${table.type}`, { kind, name: table.type });
  };

  for (const [key, kind] of Object.entries(kinds)) {
    // Definitions: [retriever.<name>], [provider.<name>], [notify.<name>].
    const defs = doc[key];
    if (isTable(defs)) for (const def of Object.values(defs)) add(kind, def);
  }

  const instances = doc.instance;
  if (Array.isArray(instances)) {
    for (const inst of instances) {
      if (!isTable(inst)) continue;
      if (typeof inst.ping_url === "string" && inst.ping_url !== "")
        ping = true;
      for (const [key, kind] of Object.entries(kinds)) {
        const list = inst[key];
        if (Array.isArray(list)) for (const item of list) add(kind, item);
      }
    }
  }
  return { plugins: [...found.values()], ping };
}
